In [1]:
#importing required modules
import pandas as pd
import numpy as np



### 1. Examine the data frame for duplicates (based on ID), and drop any duplicates that exist.

In [2]:
p_df = pd.read_csv('data/personality_scores.csv', sep=';')
p_df.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# finding the null values
p_df.isnull().sum()

ID                                                           0
Section 5 of 6 [I am always prepared.]                       0
Section 5 of 6 [I am easily disturbed.]                      0
Section 5 of 6 [I am exacting (demanding) in my work.]       0
Section 5 of 6 [I am full of ideas.]                         0
                                                          ...
Unnamed: 65                                               1555
Unnamed: 66                                               1555
Unnamed: 67                                               1555
Unnamed: 68                                               1555
IPIP_HIGH_RISK                                            1555
Length: 70, dtype: int64

In [4]:
#checking for duplicates

p_df['ID'].is_unique

True

### There are no duplicates, if we had found any we could use the function `duplicate_removal` below to remove them.

In [5]:
def duplicate_removal():
    first = len(p_df.ID)
    duplicates = len(p_df.drop_duplicates(subset='ID', keep='first'))
    return first - duplicates
duplicate_removal()

0

### Use an assert statement to check that the new data frame is the length of the unique entries of the original data frame.

Since there are no duplicates the original data has not been changed. We could check this with;
```
original_df = pd.read_csv('data/personality_scores.csv', sep=';')
clean_df = original_df.drop_duplicates(subset='ID')
assert len(original_df) == len(clean_df)
```

In [6]:
# setting index to be "ID" column in the data frame

p_df = p_df.set_index('ID')

p_df.head()
# p_df.shape

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# dropping of null values as part of the cleaning process

p_df = p_df.dropna(axis = 1)
p_df.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I often forget to put things back in their proper place],Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.]
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

### Create new columns containing the total score of each of the personality test subscales.

In [8]:
# subscaling the required columns and getting the totals for the new columns
def total_score(score, subscale):
    x = sum([eval(score[i])[1] for i in range(50) if eval(score[i])[0] == subscale])
    return(x)
# x is the total of each of the subscores

### Appending the newly created columns to the data frame

In [9]:
# adding the new columns 
p_df['Extraversion'] = p_df.apply(lambda row: total_score(row, 1), axis=1)
p_df['Agreeableness'] = p_df.apply(lambda row: total_score(row, 2), axis=1)
p_df['Conscientiousness'] = p_df.apply(lambda row: total_score(row, 3), axis=1)
p_df['Emotional Stability/Neuroticism'] = p_df.apply(lambda row: total_score(row, 4), axis=1)
p_df['Intellect/Imagination'] = p_df.apply(lambda row: total_score(row, 5), axis=1)

In [10]:
p_df.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability/Neuroticism,Intellect/Imagination
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36



* Import the data in departments.csv. Merge this data frame with the personality score data frame, keeping all applicants within the department data frame.
* Use an assert statement to check that the newly created merged data frame has the same amount of rows as the department data frame, and the expected number of columns.

In [11]:
d_df = pd.read_csv('data/departments.csv', sep=';')
d_df.head()

   ID Department
0   0       Data
1   1       Data
2   2       Data
3   3       Data
4   4       Data

### Merging departments with existing dataframe

In [12]:
full_df = pd.concat([p_df, d_df], axis=1)

In [13]:
assert len(full_df) == len(d_df)

In [14]:
print(f'From the shape of the personality data {p_df.shape} and the departments data {d_df.shape} \
we see that we should have 57 columns in the combined data frame as we have added 2 more columns, which is the case; {full_df.shape}')

From the shape of the personality data (1555, 55) and the departments data (1555, 2) we see that we should have 57 columns in the combined data frame as we have added 2 more columns, which is the case; (1555, 57)

### 4.Filter the merged data frame so that you get only the applicants who scored less than 30 on emotional stability, conscientiousness AND agreeableness. Print the ID numbers and departments of these applicants to the screen, and also assign these applicants the tag “high_risk” in a new column. All other applicants get the tag “low_risk”

In [15]:
full_df.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability/Neuroticism,Intellect/Imagination,ID,Department
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42,0,Data
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42,1,Data
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42,2,Data
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38,3,Data
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36,4,Data

In [19]:
# combined score of less than 30 from emotional stability, conscientiousness AND agreeableness. 
# define the criteria
criteria = 30
# get the variable that is less than the given criteria in all three mentioned above 
full_df[(full_df['Emotional Stability/Neuroticism'] < criteria) & \
        (full_df.Conscientiousness < criteria) & (full_df.Agreeableness < criteria)]

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability/Neuroticism,Intellect/Imagination,ID,Department,Risk
881,"(3, 3)","(4, 1)","(3, 1)","(5, 5)","(2, 1)","(5, 3)","(2, 5)","(2, 3)","(5, 3)","(1, 5)",...,"(5, 1)","(4, 1)",30,28,26,28,36,881,Data,High risk
1197,"(3, 5)","(4, 5)","(3, 1)","(5, 1)","(2, 1)","(5, 3)","(2, 5)","(2, 1)","(5, 1)","(1, 5)",...,"(5, 5)","(4, 1)",40,22,26,26,28,1197,Copywriting,High risk

In [17]:
# define what high_risk and low_risk is

full_df['Risk'] = np.where(
    (full_df['Emotional Stability/Neuroticism'] < criteria) & \
    (full_df.Conscientiousness < criteria) & (full_df.Agreeableness < criteria), 'High risk', 'Low risk'
)
full_df.head()

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.],Extraversion,Agreeableness,Conscientiousness,Emotional Stability/Neuroticism,Intellect/Imagination,ID,Department,Risk
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(5, 1)","(4, 3)",30,40,48,36,42,0,Data,Low risk
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(5, 3)","(4, 3)",42,46,46,40,42,1,Data,Low risk
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(5, 1)","(4, 3)",28,40,40,38,42,2,Data,Low risk
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(5, 1)","(4, 1)",30,38,38,40,38,3,Data,Low risk
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(5, 1)","(4, 3)",28,34,46,38,36,4,Data,Low risk

### A table showing the sum of Risk according to their departments

In [18]:
dff = full_df[['Department', 'Risk']].groupby(['Department', 'Risk']).size()
pd.DataFrame(dff)

                         0
Department  Risk
Copywriting High risk    1
            Low risk   325
Data        High risk    1
            Low risk   328
Design      Low risk   120
Strategy    Low risk   449
Web Dev     Low risk   170
Web dev     Low risk   161